### ISSUE TITLE
VS-code?

### ISSUE THREAD

**Issue by Magistern** [getflywheel/local-addon-xdebug-phpstorm#2]
Is there any chance this could somehow work with Visual Studio Code as well?

**Comment by hacknug** [comment]
Any chance we can get an answer to this now that the addon has been updated to support Local “Lightning”?

**Comment by bgturner** [comment]
This issue is specific to PHPStorm. That being said, there is a VS Code specific add-on for Local. You should be able to install it from the "Add-ons" tab within Local. Additional information can be found on the add-ons page, or the Github repo:

- https://localwp.com/add-ons/xdebug-vscode
- https://github.com/pixeljar/local-addon-xdebug-vscode
